Train NN from the Data Set

Expect to receive a 1G RR

For now, each different reactions of a specific nuclide has its own NN

In [1]:
%matplotlib inline
from IPython.display import Image
import numpy as np
import matplotlib.pyplot as plt
from math import pi
import os
import csv

from numpy import genfromtxt

import openmc
import openmc.mgxs
import openmc.model

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import optimizers

Read Training Date from CSV Files

In [2]:
n_energy = 1000
max_iters = 5

In [3]:
energy_bin= np.logspace(6, 8, num=1000)

In [4]:
flux_train = genfromtxt('flux_train.csv', delimiter=',')
n2n_train = genfromtxt('n2n_train.csv', delimiter=',')
n3n_train = genfromtxt('n3n_train.csv', delimiter=',')

### Neural Net

In [5]:
model = tf.keras.models.Sequential()
model.add(layers.Dense(5, activation='tanh'))
model.add(layers.Dense(5, activation='tanh'))
model.add(layers.Dense(1))

In [6]:
optimizer = optimizers.Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999, amsgrad=False)
model.compile(optimizer=optimizer,loss='mean_squared_error', metrics=['accuracy'])

In [7]:
def scheduler(epoch):
    if epoch < 300:
        return 0.01
    else:
        return 0.01 * np.exp(0.01 * (300 - epoch))
callback = tf.keras.callbacks.LearningRateScheduler(scheduler)

In [8]:
X_train = flux_train
Y_train = n2n_train
model.fit(X_train, Y_train, epochs=500, callbacks=[callback])

Train on 100 samples
Epoch 1/500
100/100 [==============================] - 0s 3ms/sample - loss: 0.0016 - accuracy: 0.2100
Epoch 2/500
100/100 [==============================] - 0s 154us/sample - loss: 0.0015 - accuracy: 0.2100
Epoch 3/500
100/100 [==============================] - 0s 169us/sample - loss: 9.5193e-04 - accuracy: 0.2100
Epoch 4/500
100/100 [==============================] - 0s 255us/sample - loss: 2.2006e-04 - accuracy: 0.2100
Epoch 5/500
100/100 [==============================] - 0s 188us/sample - loss: 1.7872e-04 - accuracy: 0.2100
Epoch 6/500
100/100 [==============================] - 0s 184us/sample - loss: 2.4132e-04 - accuracy: 0.2100
Epoch 7/500
100/100 [==============================] - 0s 215us/sample - loss: 3.3645e-05 - accuracy: 0.2100
Epoch 8/500
100/100 [==============================] - 0s 348us/sample - loss: 1.0481e-04 - accuracy: 0.2100
Epoch 9/500
100/100 [==============================] - 0s 194us/sample - loss: 2.3351e-05 - accuracy: 0.2100
Epoch 10

100/100 [==============================] - 0s 97us/sample - loss: 1.4651e-07 - accuracy: 0.2100
Epoch 76/500
100/100 [==============================] - 0s 153us/sample - loss: 1.1654e-07 - accuracy: 0.2100
Epoch 77/500
100/100 [==============================] - 0s 117us/sample - loss: 8.6919e-08 - accuracy: 0.2100
Epoch 78/500
100/100 [==============================] - 0s 118us/sample - loss: 7.5836e-08 - accuracy: 0.2100
Epoch 79/500
100/100 [==============================] - 0s 100us/sample - loss: 7.5958e-08 - accuracy: 0.2100
Epoch 80/500
100/100 [==============================] - 0s 115us/sample - loss: 7.0113e-08 - accuracy: 0.2100
Epoch 81/500
100/100 [==============================] - 0s 86us/sample - loss: 7.5254e-08 - accuracy: 0.2100
Epoch 82/500
100/100 [==============================] - 0s 97us/sample - loss: 7.0267e-08 - accuracy: 0.2100
Epoch 83/500
100/100 [==============================] - 0s 125us/sample - loss: 9.2102e-08 - accuracy: 0.2100
Epoch 84/500
100/100 [====

100/100 [==============================] - 0s 137us/sample - loss: 4.9518e-08 - accuracy: 0.2100
Epoch 150/500
100/100 [==============================] - 0s 111us/sample - loss: 4.9779e-08 - accuracy: 0.2100
Epoch 151/500
100/100 [==============================] - 0s 98us/sample - loss: 4.1979e-08 - accuracy: 0.2100
Epoch 152/500
100/100 [==============================] - 0s 117us/sample - loss: 5.5276e-08 - accuracy: 0.2100
Epoch 153/500
100/100 [==============================] - 0s 142us/sample - loss: 4.5581e-08 - accuracy: 0.2100
Epoch 154/500
100/100 [==============================] - 0s 138us/sample - loss: 4.6826e-08 - accuracy: 0.2100
Epoch 155/500
100/100 [==============================] - 0s 161us/sample - loss: 5.9328e-08 - accuracy: 0.2100
Epoch 156/500
100/100 [==============================] - 0s 147us/sample - loss: 1.0681e-07 - accuracy: 0.2100
Epoch 157/500
100/100 [==============================] - 0s 132us/sample - loss: 9.2198e-08 - accuracy: 0.2100
Epoch 158/500
10

Epoch 223/500
100/100 [==============================] - 0s 145us/sample - loss: 2.8894e-08 - accuracy: 0.2100
Epoch 224/500
100/100 [==============================] - 0s 101us/sample - loss: 4.0158e-08 - accuracy: 0.2100
Epoch 225/500
100/100 [==============================] - 0s 122us/sample - loss: 2.7129e-08 - accuracy: 0.2100
Epoch 226/500
100/100 [==============================] - 0s 112us/sample - loss: 5.1876e-08 - accuracy: 0.2100
Epoch 227/500
100/100 [==============================] - 0s 114us/sample - loss: 3.1873e-08 - accuracy: 0.2100
Epoch 228/500
100/100 [==============================] - 0s 112us/sample - loss: 2.9254e-08 - accuracy: 0.2100
Epoch 229/500
100/100 [==============================] - 0s 98us/sample - loss: 7.8487e-08 - accuracy: 0.2100
Epoch 230/500
100/100 [==============================] - 0s 129us/sample - loss: 5.1494e-08 - accuracy: 0.2100
Epoch 231/500
100/100 [==============================] - 0s 123us/sample - loss: 3.9889e-08 - accuracy: 0.2100
Ep

100/100 [==============================] - 0s 229us/sample - loss: 4.2025e-08 - accuracy: 0.2100
Epoch 297/500
100/100 [==============================] - 0s 120us/sample - loss: 2.8224e-08 - accuracy: 0.2100
Epoch 298/500
100/100 [==============================] - 0s 118us/sample - loss: 4.7559e-08 - accuracy: 0.2100
Epoch 299/500
100/100 [==============================] - 0s 120us/sample - loss: 4.0406e-08 - accuracy: 0.2100
Epoch 300/500
100/100 [==============================] - 0s 121us/sample - loss: 4.1960e-08 - accuracy: 0.2100
Epoch 301/500
100/100 [==============================] - 0s 144us/sample - loss: 6.4995e-08 - accuracy: 0.2100
Epoch 302/500
100/100 [==============================] - 0s 117us/sample - loss: 2.6010e-08 - accuracy: 0.2100
Epoch 303/500
100/100 [==============================] - 0s 210us/sample - loss: 1.9008e-08 - accuracy: 0.2100
Epoch 304/500
100/100 [==============================] - 0s 219us/sample - loss: 3.4918e-08 - accuracy: 0.2100
Epoch 305/500
1

100/100 [==============================] - 0s 146us/sample - loss: 9.5885e-09 - accuracy: 0.2100
Epoch 371/500
100/100 [==============================] - 0s 177us/sample - loss: 9.6966e-09 - accuracy: 0.2100
Epoch 372/500
100/100 [==============================] - 0s 132us/sample - loss: 1.6350e-08 - accuracy: 0.2100
Epoch 373/500
100/100 [==============================] - 0s 112us/sample - loss: 1.3160e-08 - accuracy: 0.2100
Epoch 374/500
100/100 [==============================] - 0s 100us/sample - loss: 1.0611e-08 - accuracy: 0.2100
Epoch 375/500
100/100 [==============================] - 0s 89us/sample - loss: 1.0456e-08 - accuracy: 0.2100
Epoch 376/500
100/100 [==============================] - 0s 91us/sample - loss: 9.3402e-09 - accuracy: 0.2100
Epoch 377/500
100/100 [==============================] - 0s 124us/sample - loss: 1.0562e-08 - accuracy: 0.2100
Epoch 378/500
100/100 [==============================] - 0s 111us/sample - loss: 9.8587e-09 - accuracy: 0.2100
Epoch 379/500
100

Epoch 444/500
100/100 [==============================] - 0s 110us/sample - loss: 1.1374e-08 - accuracy: 0.2100
Epoch 445/500
100/100 [==============================] - 0s 161us/sample - loss: 9.1744e-09 - accuracy: 0.2100
Epoch 446/500
100/100 [==============================] - 0s 117us/sample - loss: 8.4121e-09 - accuracy: 0.2100
Epoch 447/500
100/100 [==============================] - 0s 146us/sample - loss: 7.9934e-09 - accuracy: 0.2100
Epoch 448/500
100/100 [==============================] - 0s 142us/sample - loss: 8.2049e-09 - accuracy: 0.2100
Epoch 449/500
100/100 [==============================] - 0s 122us/sample - loss: 7.7733e-09 - accuracy: 0.2100
Epoch 450/500
100/100 [==============================] - 0s 133us/sample - loss: 8.0362e-09 - accuracy: 0.2100
Epoch 451/500
100/100 [==============================] - 0s 141us/sample - loss: 7.8511e-09 - accuracy: 0.2100
Epoch 452/500
100/100 [==============================] - 0s 176us/sample - loss: 8.7657e-09 - accuracy: 0.2100
E

In [9]:
flux_eval = genfromtxt('flux_eval.csv', delimiter=',')
n2n_eval = genfromtxt('n2n_eval.csv', delimiter=',')
n3n_eval = genfromtxt('n3n_eval.csv', delimiter=',')

In [10]:
n2n_pred = model.predict(flux_eval)
n2n_pred

array([[ 1.82132993e-04],
       [ 1.99147803e-03],
       [-1.48089603e-05],
       [ 6.96436362e-03],
       [ 3.15451832e-03],
       [ 2.69211689e-03],
       [ 7.49458186e-03],
       [ 3.40405223e-03],
       [ 1.10586785e-04],
       [ 3.43202788e-04]], dtype=float32)

In [11]:
n2n_eval.reshape(-1,1)

array([[3.03533652e-04],
       [1.86358510e-03],
       [8.43024822e-05],
       [6.48768098e-03],
       [2.80410859e-03],
       [2.79364438e-03],
       [7.77572398e-03],
       [3.25697941e-03],
       [0.00000000e+00],
       [5.12417109e-04]])

In [14]:
n2n_ref = model.predict(flux_train)
n2n_ref

array([[ 1.1816097e-05],
       [ 1.3041019e-05],
       [ 2.1742226e-03],
       [ 2.5297527e-04],
       [ 2.0083564e-05],
       [-8.3075662e-05],
       [ 9.1691613e-03],
       [ 2.1454008e-04],
       [ 2.1215237e-03],
       [ 4.7643908e-04],
       [ 1.4786539e-03],
       [ 6.0714607e-05],
       [ 6.2540178e-03],
       [ 2.1567650e-03],
       [ 1.1850498e-06],
       [ 2.2627690e-03],
       [ 6.1131665e-03],
       [ 5.9927872e-05],
       [ 1.0943571e-03],
       [ 5.5035274e-03],
       [ 2.3108021e-04],
       [ 1.7756429e-04],
       [ 2.6203046e-04],
       [ 6.7663412e-03],
       [-1.3875455e-05],
       [ 1.2124730e-02],
       [ 1.1796577e-04],
       [ 2.1333224e-05],
       [ 2.1002970e-03],
       [ 2.7590410e-03],
       [ 1.0343906e-04],
       [ 7.1484735e-03],
       [ 8.0154045e-05],
       [ 8.1540173e-05],
       [ 9.9507840e-03],
       [-1.4686782e-05],
       [ 2.7613931e-03],
       [ 4.5060471e-05],
       [ 7.3508481e-03],
       [ 1.6674225e-05],


In [13]:
n2n_train

array([1.08247231e-05, 0.00000000e+00, 1.96014267e-03, 3.28291040e-04,
       0.00000000e+00, 3.55383348e-06, 9.16641769e-03, 1.64865709e-05,
       2.10470476e-03, 3.82116745e-04, 1.61356891e-03, 0.00000000e+00,
       6.29758355e-03, 2.12766455e-03, 0.00000000e+00, 2.21194230e-03,
       5.98435470e-03, 0.00000000e+00, 8.04147560e-04, 5.37797193e-03,
       1.99300094e-04, 6.79887072e-05, 1.53612205e-04, 6.75691663e-03,
       1.41564926e-05, 1.20471339e-02, 0.00000000e+00, 0.00000000e+00,
       2.11189619e-03, 2.63741229e-03, 1.84855519e-06, 7.11749603e-03,
       1.27583439e-05, 1.37582784e-06, 9.91099905e-03, 0.00000000e+00,
       2.64161349e-03, 0.00000000e+00, 7.40496154e-03, 2.55687139e-05,
       0.00000000e+00, 7.59969485e-03, 1.55192856e-03, 1.31216130e-03,
       1.19783565e-06, 1.22430673e-02, 2.53343190e-03, 0.00000000e+00,
       1.42972826e-03, 6.69361330e-04, 1.79245289e-04, 2.20066157e-04,
       3.28890672e-07, 3.35247104e-03, 9.11032773e-03, 6.86783840e-04,
      